language: ruby
rvm:
  - 2.5
cache: bundler
script:
  - bundle exec rake
  - npm run linter
before_install:
  - gem update --system
  - bundle install
  - nvm install node
  - nvm use node
  - npm install
